update package.json and readme
telerik/react-coffee-warehouse pull request #16
Opened 2022-07-12 06:57 UTC by filipKovachev

https://github.com/telerik/kendo-react/issues/1151

2022-07-13 05:54 UTC, kspeyanski requested changes

2022-07-13 05:54 UTC, kspeyanski commented on package.json
>      "@progress/kendo-theme-default": "^4.36.0",
Version `4` of `@progress/kendo-theme-default` it not compatible with version `5` of the `@progress/kendo-react-*` packages.

2022-09-28 08:51 UTC, filipKovachev commented
@kspeyanski I did some testing and reverted to previous commits, the same issues can be observed there as well, after building the theme instead of loading it from the CDN for some reason those components break. Adding the theme via the CDN removes those issues.

2022-10-25 07:01 UTC, filipKovachev commented
Added the CDN, here is how everything looks on my end after removing the package-lock and reinstalling everything:

![Screenshot from 2022-10-24 22-19-21](https://user-images.githubusercontent.com/92358162/197704258-1db13781-397f-4db4-b179-84bde29b8be7.png)

![Screenshot from 2022-10-24 22-19-24](https://user-images.githubusercontent.com/92358162/197704335-327e2bc3-965d-4c93-a0cb-c9945382637d.png)

2022-11-03 12:50 UTC, vveesseelliinnaa approved these changes

2022-11-03 12:58 UTC, merged